name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  FINAL_PAGODA_TOKEN: ${{ secrets.PAGODA_CONSOLE_TOKEN }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TEMP=$(echo ${FINAL_PAGODA_TOKEN:6} | base64 --decode)" >>  $GITHUB_ENV 
      - name: Set env
        run: echo "GITHUB_REPO_FULL_NAME=$(echo ${TEMP%:*})" >> $GITHUB_ENV
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          echo "::set-output name=version::$(yarn -v)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install 🔧
        run: |
          yarn install --frozen-lockfile
      
      - name: Build Contract 🔧
        run: |
          yarn build:contract

      - name: Add repo deployment
        id: add-repo-deployment
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://e7af-94-204-65-133.in.ngrok.io/deploys/addRepoDeployment'
          method: 'POST'
          customHeaders: '{"Authorization": "${{ env.FINAL_PAGODA_TOKEN }}"}'
          data: '{"githubRepoFullName":"${{ env.GITHUB_REPO_FULL_NAME }}","commitMessage": "${{ github.event.head_commit.message }}", "commitHash": "${{ github.sha }}"}'

      - name: Upload File
        id: upload
        uses: esaminu/upload-file-action@master
        with:
          url: https://e7af-94-204-65-133.in.ngrok.io/deploys/deployWasm
          forms: '{"repoDeploymentSlug":"${{ fromJson(steps.add-repo-deployment.outputs.response).repoDeploymentSlug }}"}'
          customHeaders: '{"Authorization": "${{ env.FINAL_PAGODA_TOKEN }}"}'
          fileForms: '{"main.wasm":"contract/target/wasm32-unknown-unknown/release/deps/hello_near.wasm"}'
          
      - name: Fetch account ids
        id: fetch-account-ids
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://e7af-94-204-65-133.in.ngrok.io/deploys/contractDeployConfigs/${{fromJson(steps.add-repo-deployment.outputs.response).repoDeploymentSlug}}'
          method: 'GET'
          customHeaders: '{"Authorization": "${{ env.FINAL_PAGODA_TOKEN }}"}'
              
      - name: Build Frontend 🔧
        run: |
          yarn build:web
        env:
          CONTRACT_NAME: "${{ fromJson(steps.fetch-account-ids.outputs.response)['hello_near.wasm'].nearAccountId }}"

      - name: Upload Frontend
        id: uploadFrontend
        uses: esaminu/upload-directory-action@master
        with:
          url: https://e7af-94-204-65-133.in.ngrok.io/ipfs/add
          forms: '{}'
          customHeaders: '{"Authorization": "${{ env.FINAL_PAGODA_TOKEN }}"}'
          directory: frontend/dist

      - name: Update frontend url
        id: update-frontend-url
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://e7af-94-204-65-133.in.ngrok.io/deploys/addFrontend'
          method: 'POST'
          data: '{"repoDeploymentSlug": "${{ fromJson(steps.upload.outputs.output).data.slug }}", "cid": "${{ fromJson(steps.uploadFrontend.outputs.output).data.cid }}", "packageName": "Set Greeting Frontend" }'
          customHeaders: '{"Authorization": "${{ env.FINAL_PAGODA_TOKEN }}"}'